import { z } from "zod";

export const _flowDataJSONCore = z.object({
    media_type: z
        .literal('application/json')
        .describe('Subclassification of the format using IANA assigned media types'),
    event_type: z
        .string()
        .describe('Event type generated by this Flow, if applicable')
        .optional(),
})