import { z } from 'zod'
import { _nmosResourceBase } from './_nnosResourceBase'
import { _flowBase } from './_flowBase'

export const looseFlow = z.object({
	event_type: z.string().describe('Event type generated by this Flow, if applicable').optional(),
	sample_rate: z.object({}).passthrough().default({}),
	components: z.array(z.unknown()).default([]),
	frame_width: z.number().default(0).optional(),
	frame_height: z.number().default(0).optional(),
	interlace_mode: z.string().optional(),
	colorspace: z.string().optional(),
	transfer_characteristic: z.string().optional(),
})

const _flow = _nmosResourceBase
	.and(_flowBase)
	.and(
		z.object({
			format: z.union([
				z.literal('urn:x-nmos:format:video'),
				z.literal('urn:x-nmos:format:audio'),
				z.literal('urn:x-nmos:format:data'),
				z.literal('urn:x-nmos:format:data.event'),
				z.literal('urn:x-nmos:format:mux'),
				z.string(),
			]),
			media_type: z.union([
				z.literal('application/json'),
				z.literal('video/SMPTE2022-6'),
				z.literal('video/raw'),
				z.literal('audio/L24'),
				z.literal('audio/L20'),
				z.literal('audio/L16'),
				z.literal('audio/L8'),
				z.string().startsWith('video/'),
				z.string().startsWith('audio/'),
				z.string().startsWith('text/'),
				z.string(),
			]),
		}),
	)
	.and(looseFlow)
	.describe('Describes a Flow')

export type FlowBaseView = z.infer<typeof _flow>

export default _flow
